### ISSUE TITLE
Clarify skeleton use in the context of multiple vs single subject

### ISSUE THREAD

**Issue by h-mayorquin** [rly/ndx-pose#51]
As discussed in #18, we now have guidance suggesting that we should aim to separate different animals into different files. However, the documentation for `Skeleton` is still unclear, and I find it confusing in light of this:

```yaml
  links:
  - target_type: Subject
    doc: The Subject object in the NWB file, if this Skeleton corresponds to the Subject.
    quantity: '?'
```

https://github.com/rly/ndx-pose/blob/321a077f6f5777d0b7dc10c6a9c207b66f166219/spec/ndx-pose.extensions.yaml#L26-L29

**The confusion is: why do we need this link if all Skeletons are supposed to correspond to the same Subject? Given that the link is optional, when should it not be added?**

I think that having an optional link indicates that sometimes the Skeleton will belong to a different subject which feels at odds with the advice at #18. 

More context, the documentation for Skeletons is clearer:
https://github.com/rly/ndx-pose/blob/321a077f6f5777d0b7dc10c6a9c207b66f166219/spec/ndx-pose.extensions.yaml#L225-L231

It states that each Skeleton should correspond to a different morphology. However, this still leaves open the questions above about when and why the Subject link should be used at the Skeleton level.
