### ISSUE TITLE
Notes from discussion regarding training input

### ISSUE THREAD

**Issue by CBroz1** [rly/ndx-pose#8]
We plan to ...
1. Extend ndx-pose - check backwards compatibility
2. Assume external filepaths for images/videos
3. Check in with Mathis team regarding this development

```yaml
Pose Training input:
  Training parameters: json unspecified
  Skeletons:
    1+Skeleton:
      id: string
      1+Node Labels: string
      1+Edges: optional
  Training Frames:
    1+Training Frame:
      Annotator: optional string
      Source Video: optional
        Path: relative filepath
        Frame Index: unsigned int
      Source Frame: optional filepath
      Instances:
        1+Links to Skeleton: id
        1+Node Positions: [x, y]
```

**Comment by CBroz1** [comment]
I posted to the [DLC gitter](https://gitter.im/DeepLabCut/community) to ask for input

**Comment by roomrys** [comment]
Proposed refactoring of pose training structure:

1. Removed training parameters
2. Add attribute for node visibility
3. Add Identity group
4. Add link to instance identity

```yaml
Pose Training input:
  Identities: optional
       1+Identity: string
            name: string
            description: string
  Skeletons:
       1+Skeleton:
             id: string
             1+Node Labels: string
             1+Edges: optional
  Training Frames:
    1+Training Frame:
        Annotator: optional string
        Source Video: optional
             Path: relative filepath
             Frame Index: unsigned int
        Source Frame: optional filepath
        Instances:
             1+Links to identity: name
             1+Links to Skeleton: id
             1+Node Positions:
                  x: float
                  y: float
                  z: optional float
                  visible: bool
```
